import type { Category } from "@/data/categories";
import type { Product } from "@/data/products";
import {
  ADDRESS_LINES,
  EMAILS,
  FAX,
  FOUNDED_YEAR,
  GOOGLE_MAPS_URL,
  LEGAL_NAME,
  MOBILES,
  OFFICE_PHONE,
  SITE_NAME,
  SITE_URL,
} from "./site";
import { ANY_BRAND, productLabel } from "./whatsapp";

/** Default social share image (generated by app/opengraph-image.tsx). */
export const OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "Orient Group Gulf: HVAC, electrical and fixing materials in Kuwait",
};

export function absoluteUrl(path = "/") {
  return `${SITE_URL}${path === "/" ? "" : path}`;
}

/** Trim to a meta-description length at a word boundary. */
export function truncate(text: string, max = 158) {
  if (text.length <= max) return text;
  const cut = text.slice(0, max - 1);
  return `${cut.slice(0, cut.lastIndexOf(" ")).replace(/[,;:.\s]+$/, "")}…`;
}

export function productTitle(product: Pick<Product, "name" | "brand">) {
  return productLabel(product.name, product.brand);
}

export function productMetaDescription(product: Product) {
  return truncate(
    `${product.shortDescription} Ask for price on WhatsApp from Orient Group Gulf, Shuwaikh, Kuwait.`,
  );
}

export function categoryMetaDescription(category: Category) {
  return truncate(
    `${category.name} products in Kuwait: ${category.summary} Ask for price on WhatsApp from Orient Group Gulf, Shuwaikh.`,
  );
}

export function localBusinessJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "LocalBusiness",
    "@id": `${SITE_URL}/#business`,
    name: SITE_NAME,
    legalName: LEGAL_NAME,
    description:
      "B2B supplier of HVAC, electrical and fixing materials to MEP contractors, HVAC installers and maintenance companies in Kuwait.",
    url: SITE_URL,
    foundingDate: String(FOUNDED_YEAR),
    telephone: OFFICE_PHONE.tel,
    faxNumber: `+965${FAX.display.replace(/\s/g, "")}`,
    email: EMAILS.find((e) => e.label === "General")?.address,
    hasMap: GOOGLE_MAPS_URL,
    address: {
      "@type": "PostalAddress",
      streetAddress: ADDRESS_LINES.slice(0, 2).join(" ").replace(/,$/, ""),
      addressLocality: "Shuwaikh Industrial Area",
      addressCountry: "KW",
    },
    areaServed: { "@type": "Country", name: "Kuwait" },
    contactPoint: [
      {
        "@type": "ContactPoint",
        contactType: "sales",
        telephone: MOBILES[0].tel,
        email: EMAILS.find((e) => e.label === "Sales")?.address,
        areaServed: "KW",
      },
    ],
  };
}

/** Product schema without any price or offer (the site does not publish prices). */
export function productJsonLd(product: Product, category: Category) {
  const url = absoluteUrl(`/products/${product.slug}`);
  return {
    "@context": "https://schema.org",
    "@type": "Product",
    "@id": `${url}#product`,
    name: product.name,
    description: product.description,
    url,
    category: category.name,
    ...(product.brand !== ANY_BRAND && {
      brand: { "@type": "Brand", name: product.brand },
    }),
    ...(product.image && { image: absoluteUrl(product.image) }),
    ...(product.specs.length > 0 && {
      additionalProperty: product.specs.map((s) => ({
        "@type": "PropertyValue",
        name: s.label,
        value: s.value,
      })),
    }),
  };
}

export function breadcrumbJsonLd(items: { name: string; path: string }[]) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((item, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: item.name,
      item: absoluteUrl(item.path),
    })),
  };
}
