import type { Metadata } from "next";

import { localizeCategory, type Category } from "@/data/categories";
import { localizeProduct, type Product } from "@/data/products";
import { getDictionary } from "./dictionaries";
import { localePath, ogLocale, type Locale } from "./i18n";
import {
  ADDRESS_LINES,
  EMAILS,
  FAX,
  FOUNDED_YEAR,
  GOOGLE_MAPS_URL,
  LEGAL_NAME,
  MOBILES,
  OFFICE_PHONE,
  SITE_NAME,
  SOCIAL_LINKS,
  SITE_URL,
} from "./site";
import { ANY_BRAND, productLabel } from "./whatsapp";

/** Default social share image (generated by app/[lang]/opengraph-image.tsx). */
export const OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "Orient Group Gulf: HVAC, electrical and fixing materials in Kuwait",
};

export function absoluteUrl(path = "/") {
  return `${SITE_URL}${path === "/" ? "" : path}`;
}

/** Trim to a meta-description length at a word boundary. */
export function truncate(text: string, max = 158) {
  if (text.length <= max) return text;
  const cut = text.slice(0, max - 1);
  return `${cut.slice(0, cut.lastIndexOf(" ")).replace(/[,;:.\s،]+$/, "")}…`;
}

/**
 * Metadata for one page in one language: title, description, canonical URL,
 * hreflang links to the other language, and Open Graph tags.
 * `path` is the English path, e.g. "/products".
 */
export function pageMetadata({
  locale,
  path,
  title,
  description,
  absoluteTitle = false,
  image,
}: {
  locale: Locale;
  path: string;
  title: string;
  description: string;
  absoluteTitle?: boolean;
  image?: { url: string; alt: string };
}): Metadata {
  const t = getDictionary(locale);
  const url = localePath(locale, path);
  const fullTitle = absoluteTitle ? title : `${title} | ${t.seo.titleSuffix}`;
  return {
    title: absoluteTitle ? { absolute: title } : title,
    description: truncate(description),
    alternates: {
      canonical: url,
      languages: {
        en: localePath("en", path),
        ar: localePath("ar", path),
        "x-default": localePath("en", path),
      },
    },
    openGraph: {
      type: "website",
      siteName: SITE_NAME,
      locale: ogLocale[locale],
      alternateLocale: ogLocale[locale === "en" ? "ar" : "en"],
      title: fullTitle,
      description: truncate(description),
      url,
      images: [image ?? OG_IMAGE],
    },
  };
}

export function productTitle(product: Product, locale: Locale) {
  const label = productLabel(localizeProduct(product, locale).name, product.brand);
  // Refrigerant gas pages target "refrigerant gas Kuwait".
  return product.slug.endsWith("-refrigerant-gas")
    ? `${label} ${getDictionary(locale).seo.gasTitleSuffix}`
    : label;
}

export function productMetaDescription(product: Product, locale: Locale) {
  const t = getDictionary(locale);
  return `${localizeProduct(product, locale).shortDescription} ${t.seo.productDescriptionSuffix}`;
}

export function categoryMetaDescription(category: Category, locale: Locale) {
  const t = getDictionary(locale);
  const c = localizeCategory(category, locale);
  return t.seo.categoryDescription(c.name, c.summary);
}

export function localBusinessJsonLd(locale: Locale) {
  const t = getDictionary(locale);
  return {
    "@context": "https://schema.org",
    "@type": "LocalBusiness",
    "@id": `${SITE_URL}/#business`,
    name: SITE_NAME,
    alternateName: "أورينت جروب جلف",
    legalName: LEGAL_NAME,
    description: t.seo.defaultDescription,
    url: SITE_URL,
    foundingDate: String(FOUNDED_YEAR),
    telephone: OFFICE_PHONE.tel,
    faxNumber: `+965${FAX.display.replace(/\s/g, "")}`,
    email: EMAILS.find((e) => e.label === "General")?.address,
    hasMap: GOOGLE_MAPS_URL,
    sameAs: SOCIAL_LINKS.filter((s) => s.url).map((s) => s.url),
    address: {
      "@type": "PostalAddress",
      streetAddress: ADDRESS_LINES.slice(0, 2).join(" ").replace(/,$/, ""),
      addressLocality: "Shuwaikh Industrial Area",
      addressCountry: "KW",
    },
    areaServed: { "@type": "Country", name: "Kuwait" },
    contactPoint: [
      {
        "@type": "ContactPoint",
        contactType: "sales",
        telephone: MOBILES[0].tel,
        email: EMAILS.find((e) => e.label === "Sales")?.address,
        areaServed: "KW",
      },
    ],
  };
}

/** Product schema without any price or offer (the site does not publish prices). */
export function productJsonLd(product: Product, category: Category, locale: Locale) {
  const url = absoluteUrl(localePath(locale, `/products/${product.slug}`));
  const p = localizeProduct(product, locale);
  return {
    "@context": "https://schema.org",
    "@type": "Product",
    "@id": `${url}#product`,
    name: p.name,
    description: p.description,
    url,
    inLanguage: locale,
    category: localizeCategory(category, locale).name,
    ...(product.brand !== ANY_BRAND && {
      brand: { "@type": "Brand", name: product.brand },
    }),
    ...(product.image && { image: absoluteUrl(product.image) }),
    ...(p.specs.length > 0 && {
      additionalProperty: p.specs.map((s) => ({
        "@type": "PropertyValue",
        name: s.label,
        value: s.value,
      })),
    }),
  };
}

export function breadcrumbJsonLd(locale: Locale, items: { name: string; path: string }[]) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((item, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: item.name,
      item: absoluteUrl(localePath(locale, item.path)),
    })),
  };
}
